//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIN_GAME
    {
        public int ID { get; set; }
        public string GAME_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEAM_A { get; set; }
        public string TEAM_B { get; set; }
        public int TOTAL_POINTS { get; set; }
        public int SPECTATORS { get; set; }
        public string WINNING_TEAM { get; set; }
    }
}
